dataTree: TreeForML
data_filters:
- fY > -0.8 && fY < 0.8
- fNSigTpcTofPiExpPi < 3 && fNSigTpcTofKaExpKa < 3
- fCpa > 0.9
hh_edge:
- 2.05
high_edge: []
inputDataFile: /data/meta/BDT/DataPass4_MCPass3/Data
inputFiles:
- /data/meta/BDT/DataPass4_MCPass3/390574/
ll_edge:
- 1.66
low_edge: []
mcTree: TreeForML
mc_fd_filters:
- fOriginMcRec==2
- (fCandidateSelFlag == 1 && fFlagMcMatchRec == 1 || fCandidateSelFlag == 2 && fFlagMcMatchRec
  == -1)
- fNSigTpcTofPiExpPi < 3 && fNSigTpcTofKaExpKa < 3
- fY > -0.8 && fY < 0.8
- fM > 1.65 && fM < 2.1
- fCpa > 0.9
mc_prompt_filters:
- fOriginMcRec==1
- (fCandidateSelFlag == 1 && fFlagMcMatchRec == 1 || fCandidateSelFlag == 2 && fFlagMcMatchRec
  == -1)
- fNSigTpcTofPiExpPi < 3 && fNSigTpcTofKaExpKa < 3
- fY > -0.8 && fY < 0.8
- fM > 1.65 && fM < 2.1
- fCpa > 0.9
outDir: /data/meta/BDT/DataPass4_MCPass3/Data/sample
pTmaxs:
- 4
pTmins:
- 3
suffix: DataPass4_MCPass3_3_4
