# inputFiles: [
#   '/media/wuct/wulby/ALICE/AnRes/D0_flow/2024/TTree/MC/AO2D_MC_Pass3_medium_ptsmear1p5_phi_pt0_5_416908.root',
#   '/media/wuct/wulby/ALICE/AnRes/D0_flow/2024/TTree/MC/AO2D_MC_Pass3_medium_ptsmear1p5_phi_pt5_36_416910.root'
# ]
# outputPath: '/media/wuct/wulby/ALICE/AnRes/D0_flow/2024/TTree/MC'
# outputName: 'AO2D_MC_Pass3_medium_ptsmearing1p5_phi.root'
# isMC: True # True for MC, False for DATA

inputFiles: [
  '/media/wuct/wulby/ALICE/AnRes/D0_flow/2024/TTree/MC/AO2D_MC_Pass3_medium_ptsmearing_pt0_5_416907.root',
  '/media/wuct/wulby/ALICE/AnRes/D0_flow/2024/TTree/MC/AO2D_MC_Pass3_medium_ptsmearing_pt5_36_416909.root'
]
outputPath: '/media/wuct/wulby/ALICE/AnRes/D0_flow/2024/TTree/MC'
outputName: 'AO2D_MC_Pass3_medium_ptsmearing.root'
isMC: True # True for MC, False for DATA