# inputFiles: [
#   '/media/wuct/wulby/ALICE/AnRes/D0_flow/2024/TTree/MC/cts/AO2D_MC_Pass3_medium_ptsmearing1p5_phi_pt0_5_418439.root',
#   '/media/wuct/wulby/ALICE/AnRes/D0_flow/2024/TTree/MC/cts/AO2D_MC_Pass3_medium_ptsmearing1p5_phi_pt5_36_418441.root'
# ]
# outputPath: '/media/wuct/wulby/ALICE/AnRes/D0_flow/2024/TTree/MC/cts'
# outputName: 'AO2D_MC_Pass3_medium_ptsmearing1p5_phi.root'
# isMC: True # True for MC, False for DATA

inputFiles: [
  '/home/wuct/ALICE/otest/pure_reflection/low/AO2D.root',
  '/home/wuct/ALICE/otest/pure_reflection/high/AO2D.root'
]
outputPath: '/home/wuct/ALICE/otest/pure_reflection'
outputName: 'AO2D_MC_Pass3_medium_ptsmearing.root'
isMC: True # True for MC, False for DATA