input:
  prompt:
    [/home/wuct/ALICE/local/RTools/RTools/test/ML/McTreeForMLPromptTrain_medium_ptsmearing.root,/home/wuct/ALICE/local/RTools/RTools/test/ML/McTreeForMLPromptTrain_medium_ptsmearing1p5_phi.root]
  FD:
    [/home/wuct/ALICE/local/RTools/RTools/test/ML/McTreeForMLFDTrain_medium_ptsmearing.root,/home/wuct/ALICE/local/RTools/RTools/test/ML/McTreeForMLFDTrain_medium_ptsmearing1p5_phi.root]
  data: [/home/wuct/ALICE/local/DmesonAnalysis/RTools/ML/sample/DataTreeForMLTrain.root]
  treename: TreeForML

output:
  output_dir: /home/wuct/ALICE/local/RTools/RTools/test/Graph/Distributions/input/
  suffix: 'free'

pt_ranges:
  min: [0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 16]  # list
  max: [1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 16, 24]  # list


# [lower, upper, bins]
filters: {
  Prompt: {
      'fImpactParameterProduct': [-0.0001, 0., 10],
      'fDecayLengthXY': [0, 0.06, 15],
      'fCpa': [0.996, 1.0, 10],
      'fDecayLengthNormalised': [0, 60, 30],
      "fNSigTpcTofPiExpPi": [0, 3, 15],
      "fNSigTpcTofKaExpKa": [0, 3, 15],
      'fDecayLength': [0, 0.1, 20],
      'fDecayLengthXYNormalised': [0, 60, 15],
      'fChi2PCA': [0, 0.1, 10],
      'fCpaXY': [0.996, 1.0, 10],
      "fM": [1.65, 2.15, 120],
  },
  FD: {
      'fImpactParameterProduct': [-0.0004, 0., 20],
      'fDecayLengthXY': [0, 0.5, 25],
      'fCpa': [0.996, 1.0, 10],
      'fDecayLengthNormalised': [0, 250, 25],
      "fNSigTpcTofPiExpPi": [0, 3, 15],
      "fNSigTpcTofKaExpKa": [0, 3, 15],
      'fDecayLength': [0, 0.4, 20],
      'fDecayLengthXYNormalised': [0, 500, 25],
      'fChi2PCA': [0, 0.1, 10],
      'fCpaXY': [0.996, 1.0, 10],
      "fM": [1.55, 2.25, 120],
  }
}

plots:
  plotting_columns: [
    "fImpactParameterProduct",
    "fDecayLengthXY",
    "fCpa",
    "fDecayLengthNormalised",
    "fNSigTpcTofPiExpPi",
    "fNSigTpcTofKaExpKa",
    "fDecayLength",
    "fDecayLengthXYNormalised",
    "fChi2PCA",
    "fCpaXY",
    # "fImpactParameter0",
    # "fImpactParameter1",
    # "fImpactParameterNormalised0",
    # "fImpactParameterNormalised1",
    # "fCosThetaStar",
    # "fCt",
    "fM", 
    "fPt",
    "fPtProng0",
    "fPtProng1"
    ]
  leg_labels:
    Bkg: Background
    Prompt: [ptSmear, ptSmear1.5+phi]
    FD: [ptSmear, ptSmear1.5+phi]