# # Basic configuration
# nr: 1
# train_num: "414423"
# localpath: "/media/wuct/wulby/ALICE/AnRes/D0_flow/2024/Pass1"
# fileName: "AnalysisResults"
# max_workers: 64

# # Path copied from the Hyperloop `Submitted Jobs` page
# copypaths: [
#   /alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074064,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074063,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074062,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074061,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074060,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074058,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074056,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074055,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074054,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074053,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074052,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074051,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074050,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074049,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074048,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074047,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074046,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074045,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074044,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074043,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074042,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074041,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074040,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074039,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074038,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074037,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074036,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074035,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074034,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074033,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074032,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074031,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074030,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074029,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074028,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074027,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074026,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074025,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074024,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074023,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074022,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074021,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074020,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074019,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074018,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074017,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074016,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074015,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074014,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074013,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074012,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074011,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074010,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074009,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074008,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074007,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074006,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074005,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074004,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074003,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074002,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074001,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074000,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2073999,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2073998,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2073997,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2073996,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2073995,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2073994,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2073993,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2073992,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2073991,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2073990,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2073989,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2073988,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2073987,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2073986,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2073985,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2073984,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2073983,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2073982,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2073981,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2073980,/alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2073979
# ]
# copypaths_faild: [
#   /alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074059
# ]
# Stage_faild: [
#   Stage_1
# ]

# pass4 PbPb 20-50%cc data used to train the ML model
# nr: 16
# train_num: "390575"
# localpath: "/data/meta/BDT/DataPass4_MCPass3/Data"
# fileName: "AO2D"
# max_workers: 32
# # Path copied from the Hyperloop `Submitted Jobs` page
# copypaths: [
#   /alice/cern.ch/user/a/alihyperloop/jobs/0182/hy_1829371,/alice/cern.ch/user/a/alihyperloop/jobs/0182/hy_1829370
# ]
# subpath: 'AOD'
# subfiles: 0
# copypaths_faild: [
#   # /alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074059
# ]
# Stage_faild: [
#   # Stage_1
# ]
# nr: 28
# train_num: "390574"
# localpath: "/data/meta/BDT/DataPass4_MCPass3/Data"
# fileName: "AO2D"
# max_workers: 32
# # Path copied from the Hyperloop `Submitted Jobs` page
# copypaths: [
#   /alice/cern.ch/user/a/alihyperloop/jobs/0182/hy_1829369,/alice/cern.ch/user/a/alihyperloop/jobs/0182/hy_1829368
# ]
# subpath: 'AOD'
# subfiles: 0
# copypaths_faild: [
#   # /alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074059
# ]
# Stage_faild: [
#   # Stage_1
# ]

# # Pass3 PbPb 20-50%cc
# nr: 16
# train_num: ""
# localpath: "/home/wuct/ALICE/local/RTools/Meta/MC/pass3/544122_1"
# fileName: "AO2D"
# max_workers: 10

# # Path copied from the Hyperloop `Submitted Jobs` page
# copypaths: [
#   /alice/sim/2024/LHC24g2/0/544122/AOD/574,
#   /alice/sim/2024/LHC24g2/1/544122/AOD/526,
#   /alice/sim/2024/LHC24g2/1/544122/AOD/453,
#   /alice/sim/2024/LHC24g2/0/544122/AOD/350,
#   /alice/sim/2024/LHC24g2/0/544122/AOD/042,
#   /alice/sim/2024/LHC24g2/0/544122/AOD/053,
#   /alice/sim/2024/LHC24g2/0/544122/AOD/065,
#   /alice/sim/2024/LHC24g2/2/544122/AOD/121,
#   /alice/sim/2024/LHC24g2/0/544122/AOD/230,
#   /alice/sim/2024/LHC24g2/0/544122/AOD/289,

# ]
# subfiles: 0 # used to download the metadata files
# copypaths_faild: [
#   # /alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074059
# ]
# Stage_faild: [
#   # Stage_1
# ]

# nr: 99
# train_num: "448943"
# localpath: "/data/meta/BDT/DataPass4_MCPass4/Data"
# fileName: "AO2D"
# max_workers: 32
# # Path copied from the Hyperloop `Submitted Jobs` page
# copypaths: [
#   /alice/cern.ch/user/a/alihyperloop/jobs/0239/hy_2399620,/alice/cern.ch/user/a/alihyperloop/jobs/0239/hy_2399619
# ]
# subpath: 'AOD'
# subfiles: 0
# copypaths_faild: [
#   # /alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074059
# ]
# Stage_faild: [
#   # Stage_1
# ]

nr: 16
train_num: "mc_med_ITS_459444_picked"
localpath: "/data/meta/AnRes/flow/pass4/T03_occupancy_ITS_FT0c"
fileName: "AnalysisResults.root"
max_workers: 32
copypaths: ['/alice/cern.ch/user/a/alihyperloop/jobs/0249/hy_2499347', '/alice/cern.ch/user/a/alihyperloop/jobs/0249/hy_2499346', '/alice/cern.ch/user/a/alihyperloop/jobs/0249/hy_2499345', '/alice/cern.ch/user/a/alihyperloop/jobs/0249/hy_2499344', '/alice/cern.ch/user/a/alihyperloop/jobs/0249/hy_2499343', '/alice/cern.ch/user/a/alihyperloop/jobs/0249/hy_2499342', '/alice/cern.ch/user/a/alihyperloop/jobs/0249/hy_2499341', '/alice/cern.ch/user/a/alihyperloop/jobs/0249/hy_2499340']
subpath: ''
subfiles: 0
copypaths_faild: [
  # /alice/cern.ch/user/a/alihyperloop/jobs/0207/hy_2074059
]
Stage_faild: [
  # Stage_1
]

# nr: 16
# train_num: "data_med_FT0c_468349"
# localpath: "/data/meta/AnRes/flow/pass4/T03_occupancy_ITS_FT0c"
# fileName: "AnalysisResults.root"
# max_workers: 32
# copypaths: [
#   /alice/cern.ch/user/a/alihyperloop/jobs/0257/hy_2579405,/alice/cern.ch/user/a/alihyperloop/jobs/0257/hy_2579399,/alice/cern.ch/user/a/alihyperloop/jobs/0257/hy_2579388,/alice/cern.ch/user/a/alihyperloop/jobs/0257/hy_2579302,/alice/cern.ch/user/a/alihyperloop/jobs/0257/hy_2579294,/alice/cern.ch/user/a/alihyperloop/jobs/0257/hy_2579293,/alice/cern.ch/user/a/alihyperloop/jobs/0257/hy_2579292
# ]
# subpath: ''
# subfiles: 0
# copypaths_faild: [
#   /alice/cern.ch/user/a/alihyperloop/jobs/0257/hy_2579421
# ]
# Stage_faild: [
#   Stage_1
# ]

# nr: 16
# train_num: "462529"
# localpath: "/data/meta/AnRes/flow/NeNe/pass1"
# fileName: "AnalysisResults.root"
# max_workers: 32
# copypaths: [
#   /alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2528473,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2528472
# ]
# subpath: ''
# subfiles: 0
# copypaths_faild: [
#   /alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2528472
# ]
# Stage_faild: [
#   Stage_1
# ]

# nr: 16
# train_num: "462297"
# localpath: "/data/meta/BDT/DataPass4_MCPass4/Mc"
# fileName: "AO2D.root"
# max_workers: 32
# copypaths: [

#   /alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523842,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523841,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523840,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523839,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523838,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523836,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523835,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523834,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523833,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523832,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523831,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523830,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523829,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523828,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523827,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523826,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523825,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523824,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523823,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523822,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523821,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523820,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523819,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523818,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523817,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523816,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523815,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523814,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523813,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523812,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523811,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523810,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523809,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523808,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523807,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523806,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523805,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523804,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523803,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523802,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523801,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523800,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523799,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523798,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523797,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523796,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523793,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523792,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523791,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523790,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523789,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523788,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523787,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523786,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523785,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523784,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523783,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523782,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523781,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523780,/alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2523779

# ]
# subpath: 'AOD'
# subfiles: 0
# copypaths_faild: [
#   # /alice/cern.ch/user/a/alihyperloop/jobs/0252/hy_2528472
# ]
# Stage_faild: [
#   # Stage_1
# ]